# Generated by Django 4.0.5 on 2022-06-30 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_img1',
        ),
    ]
