# Generated by Django 4.0.5 on 2023-02-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='intro_description',
            field=models.TextField(blank=True),
        ),
    ]
