# Generated by Django 4.0.5 on 2023-02-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_intro_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_img_2',
            field=models.ImageField(blank=True, upload_to='photos/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_img_3',
            field=models.ImageField(blank=True, upload_to='photos/products'),
        ),
    ]
