# Generated by Django 4.0.5 on 2023-02-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subtitle1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle2',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
