# Generated by Django 4.0.5 on 2023-03-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_subtitle1_product_subtitle2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_img_4',
            field=models.ImageField(blank=True, upload_to='photos/products'),
        ),
    ]
